stages:
  - develop
  - build
  - scan
  - sign
  - release
  - deploy

include:
  - component: $CI_SERVER_FQDN/dev/lts-cicd/container@main
    inputs:
      image_name: scouticket
  - component: $CI_SERVER_FQDN/dev/lts-cicd/semantic-release@main
